global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'quiz-app-cluster'
    environment: 'production'

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Quiz Application
  - job_name: 'quiz-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['quiz-app:8080']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'quiz-app'

  # PostgreSQL Exporter (if using postgres_exporter)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'postgres-db'

  # Node Exporter (if monitoring host metrics)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

rule_files:
  # - "alert.rules.yml"
